name: Flat
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/flat.yml
      - update_feedbin.js
  workflow_dispatch: null
  schedule:
    - cron: 0 0 * * *
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.x
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: https://api.feedbin.com/v2/starred_entries.json
          downloaded_filename: entries.tmp.json
          authorization: ${{ secrets.AUTHORIZATION }}
          postprocess: update_feedbin.js
        env:
          AUTHORIZATION: ${{ secrets.AUTHORIZATION }}
